project_id = "pythoncurso-402901"
region     = "us-central1"
ent_terraform = "entrada_terraform"
schema_bucket = "entrada_schema_bucket"
entrada_manual = "entrada_manual"
entrada_auto = "entrada_auto"
